### ISSUE TITLE
where the windows support

### ISSUE THREAD

**Issue by LisieDoesCode** [AFellowSpeedrunner/LUM-MARINER#3]
i am massive fan, have sucked off bill gates before and feel it is nessisary for windows to be supported in running this inferior operating system

**Comment by AFellowSpeedrunner** [comment]
Ah yes, you're correct. I apologise for my severe lapse in judgement. Windows (despite being not at all suitable for OSDev in any way) should be supported. Let me update it.

**Comment by LisieDoesCode** [comment]
ps. i use Windows 11, version 23H2 btw

**Comment by AFellowSpeedrunner** [comment]
There we go. Should help.

**Comment by AFellowSpeedrunner** [comment]
Had a change of heart. Here is actual build instructions. Check the readme.
